//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarView
{
    using System;
    
    public enum SemesterEnum : int
    {
        Winter = 1,
        Spring = 2,
        Summer = 3,
        Fall = 4
    }
}
